refactor(filecoin-proofs): use _f64 type
Clippy emits error:

        error: casting integer literal to `f64` is unnecessary

Use `32_f64` as suggested instead of casting to an `f64`.