refactor(storage-proofs): remove reference from match pattern
Clippy emits error:

        error: you don't need to add `&` to all patterns

Along with the suggestion to dereference the expression instead of
prefixing all patters with `&`.

Do as suggested by clippy and dereference the expressions.