refactor(filecoin-proofs): no function call after expect
Clippy emits error:

        error: use of `expect` followed by a function call

Do as suggested by clippy and use `unwrap_or_else()` coupled with
`panic!` instead of calling `format!` as an argument to `expect()`.