chore: fix building master branch
The current build fails due to:

error: package `home v0.5.11` cannot be built because it requires rustc 1.81
or newer, while the currently active rustc version is 1.70.0

This commit increases the Rust version from 1.70.0 to 1.81.0.

It also fixes all Clippy warnings that were introduced in the newer Rust versions.