refactor(storage-proofs): use copy instead of clone
Clippy emits error:

	error: using `clone` on a `Copy` type

This type implements `Copy`, we can copy it instead of cloning.

Closes: #1113