refactor(filecoin-proofs): allow identity_op in test
Clippy emits error:

  error: the operation is ineffective. Consider reducing it to `127`

This is caused because we use `1 * 127` in order to be consistent with
other usages i.e., `2 * 127` and `8 * 127`. Clippy is wrong in this
instance, the ineffective operation makes the code easier to read.

Instruct clippy to allow this lint.