refactor(filecoin-proofs): use write_all
Clippy emits error:

 error: written amount is not handled. Use `Write::write_all` instead

Use `write_all` as clippy suggests since we do not use the return
result.