refactor(filecoin-proofs): use iterator instead of indexing
Clippy emits error:

        error: the loop variable `i` is used to index `val`

Use an iterator, as suggested, to loop over the arrays of bytes. Use
combinators `skip` and `take` as needed.