fix: make arguments mutually exclusive
The command line argumens `--only-post` and `--only-sector-update` are mutually
exclusive. With this commit you'll get an error message if both are used at the
same time:

    error: The argument '--only-sector-update' cannot be used with one or more of the other specified arguments

    USAGE:
        paramcache --api-version <SEMANTIC VERSION> <--only-post|--only-sector-update>

    For more information try --help